# Generated by Django 4.2.4 on 2023-08-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('account_location', models.CharField(choices=[('PRB', 'Private Bank'), ('PBB', 'Public Bank'), ('PO', 'Post Office')], max_length=3)),
                ('account_balance', models.FloatField(default=10000)),
                ('monthly_expenses', models.BigIntegerField(default=10000)),
                ('monthly_salary', models.BigIntegerField(default=25000)),
                ('government_id', models.CharField(max_length=12)),
                ('net_worth', models.BigIntegerField(default=0)),
                ('kindness_index', models.PositiveSmallIntegerField(default=20)),
            ],
        ),
    ]
