# Generated by Django 4.2.4 on 2023-08-10 12:57

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.FloatField()),
                ('interest', models.FloatField()),
                ('term', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(choices=[('PRB', 'Private Bank'), ('PBB', 'Public Bank'), ('PO', 'Post Office')], max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='CharityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('AP', 'Apartment'), ('IH', 'Individual House'), ('PL', 'Plot')], max_length=3)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('buying_price', models.FloatField()),
                ('value', models.FloatField()),
                ('location', models.CharField(choices=[('PRB', 'Private Bank'), ('PBB', 'Public Bank'), ('PO', 'Post Office')], max_length=3)),
                ('owner', models.ForeignKey(default=mainapp.models.Player.get_default_entity_pk, on_delete=django.db.models.deletion.SET_DEFAULT, to='mainapp.player')),
            ],
        ),
    ]
