# Generated by Django 4.2.4 on 2023-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_fixeddeposit_charitytransaction_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposit',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('B', 'Broken'), ('C', 'Completed')], default='O', max_length=1),
        ),
    ]
