# Generated by Django 4.2.4 on 2023-08-14 11:56

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_player_happiness_index_player_wallet_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('purpose', models.CharField(choices=[('CH', 'Charity'), ('WW', 'WithdrawalFromWallet'), ('DW', 'DepositToWallet'), ('EM', 'Emergency'), ('SH', 'Shopping')], max_length=2)),
                ('beneficiary', models.ForeignKey(default=mainapp.models.Player.get_deleted_entity_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='beneficiary', to='mainapp.player')),
                ('depositor', models.ForeignKey(default=mainapp.models.Player.get_deleted_entity_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='depositor', to='mainapp.player')),
            ],
        ),
        migrations.DeleteModel(
            name='CharityTransaction',
        ),
    ]
