# Generated by Django 4.2.4 on 2023-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_fixeddeposittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeddeposittype',
            name='restricted_to_gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('N', 'NEITHER')], max_length=1, null=True),
        ),
    ]
