# Generated by Django 4.2.4 on 2023-08-15 19:06

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_fixeddeposittype_restricted_to_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='fixeddeposit',
            name='term',
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='fixed_deposit_type',
            field=models.ForeignKey(default=mainapp.models.FixedDepositType.get_default_entity_pk, on_delete=django.db.models.deletion.CASCADE, to='mainapp.fixeddeposittype'),
        ),
    ]
