# Generated by Django 4.2.4 on 2023-08-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_fixeddeposit_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.AddField(
            model_name='asset',
            name='up_for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
