# Generated by Django 4.2.4 on 2023-08-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_asset_location_asset_up_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('CH', 'Charity'), ('WW', 'WithdrawalFromWallet'), ('DW', 'DepositToWallet'), ('EM', 'Emergency'), ('SH', 'Shopping'), ('BA', 'BuyAsset')], max_length=2),
        ),
    ]
