# Generated by Django 4.2.4 on 2023-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_transaction_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='account_location',
            field=models.CharField(choices=[('PRB', 'Private Bank'), ('PBB', 'Public Bank'), ('PO', 'Post Office')], max_length=3, null=True),
        ),
    ]
